### ISSUE TITLE
[1.16.x] Issues megathread

### ISSUE THREAD

**Issue by reo-ar** [yuitakaa/InvTweaksReborn#4]
Reply to this with your crash log, latest log, or feature suggestions for 1.16.1

TODO:

- [x] Quickview does not work on latest 1.16.1

- [x] Tag sorting does not work

- [x] Does not work when used client-side only (Forge problem?)

- [x] Does not work well with multiplayer servers.

**Comment by penut85420** [comment]
I encounter a crash when I sort in chestbox in friend's server (vanilla).
The error message:
```
The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: mouseClicked event handler
```
Here's the crash report [crash-2020-07-03_08.44.51-client.txt](https://github.com/reo-ar/InvTweaksRenewed/files/4867196/crash-2020-07-03_08.44.51-client.txt).

**Comment by matthewdm0816** [comment]
> I encounter a crash when I sort in chestbox in friend's server (vanilla).
> The error message:
> 
> ```
> The game crashed whilst mouseclicked event handler
> Error: java.lang.NullPointerException: mouseClicked event handler
> ```
> 
> Here's the crash report [crash-2020-07-03_08.44.51-client.txt](https://github.com/reo-ar/InvTweaksRenewed/files/4867196/crash-2020-07-03_08.44.51-client.txt).

My situation very similar with you and my solution for share

Initially:
Forge 32.0.47(Newest up to then)+ optifine pre2 + this plugin 1.0.2 = wrong rendering + crash on many clicks of sort | Pure MC  Server(no forge/mods)
So I tried to fix render prob. => Forge 32.0.40-32.0.25(referring to changelog of optifine, 32.0.25 is supported for sure) rendering works + crash still(tried forge ver.: .25, .30, .35, .40)
Then I realized it's a prob. of mismatch Forge ver. used/in development => check plugin update date => according to the date to select corresponding ver. of Forge used => 32.0.20
Solution:
Forge 32.0.20 + Optifine pre2 + this plugin 1.0.2 = works fine for now 
Reason: 
Might due to rapid updates of forge(just common to see of early time of a new ver. of mc)

And sincere thanks for the work in this great mod!(the first available under: 1.16.1 & optifine(which requires must forge rather than fabric) to my best knowledge)

**Comment by reo-ar** [comment]
I've not been updating this to the newest Forge changes yet, as mappings are unstable, but I will update it asap once the new mappings are released.

**Comment by reo-ar** [comment]
Update has dropped, try the changes out.

**Comment by aleungplants** [comment]
Issues with multiplayer. When pressing the sort button, it doesn't sort fully (for example one type of item is kind of everywhere, while some others are sorted). Sometimes there are empty spots/gaps in the items. Each press also sometimes yields different results. Spamming the button makes the game crash.

[crash-2020-07-14_12.31.32-client.txt](https://github.com/reo-ar/InvTweaksRenewed/files/4950229/crash-2020-07-14_12.31.32-client.txt)

**Comment by L-Clouds** [comment]
Same experience as leungarthur playing on a vanilla server.

[crash-2020-07-13_02.45.50-client.txt](https://github.com/reo-ar/InvTweaksRenewed/files/4924148/crash-2020-07-13_02.45.50-client.txt)
[crash-2020-07-13_01.59.19-client.txt](https://github.com/reo-ar/InvTweaksRenewed/files/4924149/crash-2020-07-13_01.59.19-client.txt)

**Comment by Exotic0015** [comment]
Same for me when playing on a vanilla server. In addition to crashes, sorting doesn't work well (same issue as leungarthur's).
[crash-2020-07-17_22.45.30-client.txt](https://github.com/reo-ar/InvTweaksRenewed/files/4940177/crash-2020-07-17_22.45.30-client.txt)

**Comment by TeamDman** [comment]
[crash-2020-07-25_18.10.57-client.txt](https://github.com/reo-ar/InvTweaksRenewed/files/4976707/crash-2020-07-25_18.10.57-client.txt)

**Comment by Darinth** [comment]
Same issue. Logging into my multiplayer vanilla server. Sorting appears to work fine as long as there is no more than 1 stack of an item. The second it sees a second stack of something it is unhappy and won't sort them in any consistent fashion. May crash on the first attempt to sort, may wait till the 5th or 15th attempt to sort.
[crash-2020-08-06_10.53.24-client.txt](https://github.com/reo-ar/InvTweaksRenewed/files/5035717/crash-2020-08-06_10.53.24-client.txt)

**Comment by reo-ar** [comment]
Please check the new versions and try to sort with this mod on client-side only.

**Comment by Darinth** [comment]
Seems to be working fine. Thank you for the work!

**Comment by reo-ar** [comment]
Version seems stable now, will close.
